/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API info
         * @description Returns basic API information
         */
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contacts
         * @description Lists contacts with pagination and filtering
         */
        get: operations["getV1Contacts"];
        put?: never;
        /**
         * Create contact
         * @description Creates a new contact with optional topic subscriptions
         */
        post: operations["postV1Contacts"];
        /**
         * Bulk delete contacts
         * @description Deletes multiple contacts at once (max 100)
         */
        delete: operations["deleteV1Contacts"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get contact
         * @description Returns a single contact by ID with topic subscriptions
         */
        get: operations["getV1ContactsById"];
        put?: never;
        post?: never;
        /**
         * Delete contact
         * @description Deletes a single contact
         */
        delete: operations["deleteV1ContactsById"];
        options?: never;
        head?: never;
        /**
         * Update contact
         * @description Updates an existing contact
         */
        patch: operations["patchV1ContactsById"];
        trace?: never;
    };
    "/v1/batch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create batch send
         * @description Creates a new batch send job and queues it for processing
         */
        post: operations["postV1Batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batch/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get batch status
         * @description Returns the current status of a batch send job
         */
        get: operations["getV1BatchById"];
        put?: never;
        post?: never;
        /**
         * Cancel batch send
         * @description Cancels a scheduled or queued batch send. If scheduled, also deletes the EventBridge schedule.
         */
        delete: operations["deleteV1BatchById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/ses/{awsAccountNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive SES events
         * @description Webhook endpoint for receiving SES events from EventBridge API Destination. The awsAccountNumber is the 12-digit AWS account ID.
         */
        post: operations["postWebhooksSesByAwsAccountNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unsubscribe/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsubscribe confirmation page
         * @description Shows a confirmation page for users who click the unsubscribe link in emails. Displays a form to confirm the unsubscribe action.
         */
        get: operations["getUnsubscribeByToken"];
        put?: never;
        /**
         * One-click unsubscribe (RFC 8058)
         * @description Processes unsubscribe requests. Supports RFC 8058 one-click unsubscribe via POST with body 'List-Unsubscribe=One-Click'. Returns 200 OK directly (no redirects per RFC 8058 spec).
         */
        post: operations["postUnsubscribeByToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getV1Contacts: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                emailStatus?: string;
                smsStatus?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postV1Contacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email?: string;
                    phone?: string;
                    emailStatus?: "active" | "unsubscribed" | "bounced" | "complained";
                    smsStatus?: "pending_consent" | "opted_in" | "opted_out" | "invalid";
                    properties?: {
                        [key: string]: unknown;
                    };
                    topicIds?: string[];
                    topicSlugs?: string[];
                };
                "multipart/form-data": {
                    email?: string;
                    phone?: string;
                    emailStatus?: "active" | "unsubscribed" | "bounced" | "complained";
                    smsStatus?: "pending_consent" | "opted_in" | "opted_out" | "invalid";
                    properties?: {
                        [key: string]: unknown;
                    };
                    topicIds?: string[];
                    topicSlugs?: string[];
                };
                "text/plain": {
                    email?: string;
                    phone?: string;
                    emailStatus?: "active" | "unsubscribed" | "bounced" | "complained";
                    smsStatus?: "pending_consent" | "opted_in" | "opted_out" | "invalid";
                    properties?: {
                        [key: string]: unknown;
                    };
                    topicIds?: string[];
                    topicSlugs?: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteV1Contacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                };
                "multipart/form-data": {
                    ids: string[];
                };
                "text/plain": {
                    ids: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getV1ContactsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteV1ContactsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchV1ContactsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email?: string;
                    phone?: string;
                    emailStatus?: "active" | "unsubscribed" | "bounced" | "complained";
                    smsStatus?: "pending_consent" | "opted_in" | "opted_out" | "invalid";
                    properties?: {
                        [key: string]: unknown;
                    };
                    topicIds?: string[];
                    topicSlugs?: string[];
                };
                "multipart/form-data": {
                    email?: string;
                    phone?: string;
                    emailStatus?: "active" | "unsubscribed" | "bounced" | "complained";
                    smsStatus?: "pending_consent" | "opted_in" | "opted_out" | "invalid";
                    properties?: {
                        [key: string]: unknown;
                    };
                    topicIds?: string[];
                    topicSlugs?: string[];
                };
                "text/plain": {
                    email?: string;
                    phone?: string;
                    emailStatus?: "active" | "unsubscribed" | "bounced" | "complained";
                    smsStatus?: "pending_consent" | "opted_in" | "opted_out" | "invalid";
                    properties?: {
                        [key: string]: unknown;
                    };
                    topicIds?: string[];
                    topicSlugs?: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postV1Batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    channel?: "email" | "sms";
                    name?: string;
                    audienceType?: "all" | "topic" | "segment";
                    topicId?: string;
                    segmentId?: string;
                    subject?: string;
                    previewText?: string;
                    from?: string;
                    fromName?: string;
                    replyTo?: string;
                    templateId?: string;
                    htmlContent?: string;
                    body?: string;
                    senderId?: string;
                    scheduledFor?: string;
                    awsAccountId: string;
                    totalRecipients?: number;
                };
                "multipart/form-data": {
                    channel?: "email" | "sms";
                    name?: string;
                    audienceType?: "all" | "topic" | "segment";
                    topicId?: string;
                    segmentId?: string;
                    subject?: string;
                    previewText?: string;
                    from?: string;
                    fromName?: string;
                    replyTo?: string;
                    templateId?: string;
                    htmlContent?: string;
                    body?: string;
                    senderId?: string;
                    scheduledFor?: string;
                    awsAccountId: string;
                    totalRecipients?: number;
                };
                "text/plain": {
                    channel?: "email" | "sms";
                    name?: string;
                    audienceType?: "all" | "topic" | "segment";
                    topicId?: string;
                    segmentId?: string;
                    subject?: string;
                    previewText?: string;
                    from?: string;
                    fromName?: string;
                    replyTo?: string;
                    templateId?: string;
                    htmlContent?: string;
                    body?: string;
                    senderId?: string;
                    scheduledFor?: string;
                    awsAccountId: string;
                    totalRecipients?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        status: string;
                        channel: string;
                        totalRecipients: number;
                        createdAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        status: string;
                        channel: string;
                        totalRecipients: number;
                        createdAt: string;
                    };
                    "text/plain": {
                        id: string;
                        status: string;
                        channel: string;
                        totalRecipients: number;
                        createdAt: string;
                    };
                };
            };
        };
    };
    getV1BatchById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteV1BatchById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        id: string;
                        status: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        id: string;
                        status: string;
                    };
                    "text/plain": {
                        success: boolean;
                        id: string;
                        status: string;
                    };
                };
            };
        };
    };
    postWebhooksSesByAwsAccountNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                awsAccountNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUnsubscribeByToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postUnsubscribeByToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
                "multipart/form-data": unknown;
                "text/plain": unknown;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
