export { WrapsEmail } from './client';
export { BatchError, DynamoDBError, SESError, ValidationError, WrapsEmailError } from './errors';
export { WrapsEmailEvents } from './events';
export { WrapsInbox } from './inbox';
export { WrapsEmailSuppression } from './suppression';
export type {
  Attachment,
  BatchEmailEntry,
  BatchEntryResult,
  BulkTemplateDestination,
  CreateTemplateFromReactParams,
  CreateTemplateParams,
  EmailAddress,
  EmailEvent,
  EmailListOptions,
  EmailListResult,
  EmailStatus,
  InboxAttachment,
  InboxEmail,
  InboxEmailAddress,
  InboxEmailSummary,
  InboxForwardOptions,
  InboxGetAttachmentOptions,
  InboxListOptions,
  InboxListResult,
  InboxReplyOptions,
  SendBatchParams,
  SendBatchResult,
  SendBulkTemplateParams,
  SendBulkTemplateResult,
  SendEmailParams,
  SendEmailResult,
  SendTemplateParams,
  SuppressionEntry,
  SuppressionListOptions,
  SuppressionListResult,
  SuppressionReason,
  Template,
  TemplateMetadata,
  UpdateTemplateParams,
  WrapsEmailConfig,
} from './types';
